global:
  hosts:
    domain: gitlab.local
    externalIP: 127.0.0.1
    https: false
  ingress:
    configureCertmanager: false
    class: traefik
  certmanager:
    install: false
  psql:
    host: pg-postgresql.gitlab.svc.cluster.local
    port: 5432
    username: gitlab
    database: gitlabhq_production
    password:
      secret: pg-postgresql
      key: postgres-password
  redis:
    host: rd-redis-master.gitlab.svc.cluster.local
    auth:
      secret: rd-redis
      key: redis-password
  minio:
    enabled: true
  appConfig:
    object_store:
      enabled: false
      connection: {}
    lfs:
      enabled: false
      connection: {}
    artifacts:
      enabled: false
      connection: {}
    uploads:
      enabled: false
      connection: {}
    packages:
      enabled: false
      connection: {}
    backups:
      object_store:
        enabled: false
        connection: {}

certmanager-issuer:
  email: ialdidi@student.1337.ma

nginx-ingress:
  enabled: false

registry:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

kas:
  enabled: false

postgresql:
  install: false

redis:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1