Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus   = 1
    lv.driver = "kvm"
  end

  config.vm.define "ialdidiS" do |server|
    server.vm.hostname = "ialdidiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

end