Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus   = 1
    lv.driver = "kvm"
  end

  # ── First machine: Server (control plane) ──────────────────────────────────
  config.vm.define "ialdidiS" do |server|
    server.vm.hostname = "ialdidiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # ── Second machine: ServerWorker (agent) ───────────────────────────────────
  config.vm.define "ialdidiSW" do |worker|
    worker.vm.hostname = "ialdidiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end

end
